# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stacja IT - Złap pociąg do kodowania
email: kontakt@stacja.it
description: >
  Stacja IT to całodniowe warsztaty hands-on, bezpłatna edukacja trenerska,
  miejsce spotkań ekspertów branżowych, profesjonalistów, którzy nieprzerwanie
  podnoszą swoje kompetencje, trenerów, przedsiębiorców i twórców startupów,
  a także osób wchodzących na rynek pracy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stacja.it" # the base hostname & protocol for your site

gems:
  - jekyll-seo-tag

twitter:
  username: stacjait

# Build settings
markdown: kramdown

collections:
  warsztaty:
    output: true

defaults:
 - scope:
      path: ""
      type: warsztaty
   values:
      layout: event

exclude:
    - node_modules
